### ISSUE TITLE
Client Update Measures

### ISSUE THREAD

**Issue by Zehra** [allejo/LeagueOverseer#53]
I'm thinking since the league is able to disallow game clients for being outdated, why not have a feature which permits this to be done automatically?

I'm not sure if I'm correct, but in 2.4.x there seems to be a "version" area in **bz_BasePlayerRecord**.
This could be used to get the client version from a client.
If the client version is outdated, it could be kicked with a message.
"Game client outdated, please update to [version]."

It would make it easier to force an upgrade and also to prevent outdated client versions from joining too.

**Comment by allejo** [comment]
When was the last time this functionality was even needed though? BZ devs are really careful with protobreaks so it's not like one client will has an advantage over others.

**Comment by Zehra** [comment]
> Players are encouraged to use the latest version of the BZFlag game client version available for their operating system. However, any client version which is compatible with the protocol version used by official league match servers may be used. An exception is if the league administrators announce on the league discussion forum of the BZFlag Bulletin Board that a specific outdated client version is no longer allowed, which may be due to any sufficiently compelling reason.

It basically isn't needed yet, but if for any reason a league decides to make a specific version outdated, they will have a tool ready for this and able to force an upgrade easily.

Also, I forgot to mention that it could be used in a manner of the nagware plug-in, except instead of encouraging players to register, it could encourage them to update their client.

**Comment by allejo** [comment]
I'm reluctant to incorporate this into LO or make it as a plugin in general. While the idea is nice and the rule is there, this isn't something I'd be ok with enforcing. Reason being that BZFlag doesn't have a good way of pushing out updates to Linux distributions. Unless people compile the client themselves, they'd be stuck with whatever the distribution provides which is often an outdated version.

I'd be ok with revisiting this if BZFlag starts distributing client updates to Linux easily or if updates are incorporated into the 2.6.x launcher.
